"""
İthalat Fırsat Analizi — TradeTrend v0.2
Türkiye'de talebi yüksek, yerli arzın yetersiz kaldığı ürünleri tespit eder.
Algoritma: import_score = demand_score * 0.55 + supply_gap * 0.45
"""

from dataclasses import dataclass, field
from typing import List


@dataclass
class ImportOpportunity:
    product_name: str
    subcategory: str
    demand_score: float        # 0-100 TR talebi
    local_supply_score: float  # 0-100 yerli arz
    import_score: float        # fırsat skoru
    monthly_searches_tr: int   # tahmini aylık TR araması
    foreign_platforms: List[str]
    avg_price_usd: int
    avg_price_try: int
    trend_direction: str       # "rising_fast" | "rising" | "stable"
    opportunity_label: str     # "Yüksek Fırsat" | "Orta Fırsat" | "Takipte"
    insight: str

    @property
    def supply_gap(self) -> float:
        return round(max(0.0, self.demand_score - self.local_supply_score), 1)

    def to_dict(self) -> dict:
        return {
            "product_name":        self.product_name,
            "subcategory":         self.subcategory,
            "demand_score":        self.demand_score,
            "local_supply_score":  self.local_supply_score,
            "supply_gap":          self.supply_gap,
            "import_score":        self.import_score,
            "monthly_searches_tr": self.monthly_searches_tr,
            "foreign_platforms":   self.foreign_platforms,
            "avg_price_usd":       self.avg_price_usd,
            "avg_price_try":       self.avg_price_try,
            "trend_direction":     self.trend_direction,
            "opportunity_label":   self.opportunity_label,
            "insight":             self.insight,
        }


IMPORT_DATA: dict = {

    "kirtasiye": [
        ImportOpportunity(
            "Washi Tape Koleksiyonu", "Sanat & Dekor",
            demand_score=88, local_supply_score=28, import_score=82,
            monthly_searches_tr=45_000,
            foreign_platforms=["AliExpress", "Etsy", "Rakuten Japan"],
            avg_price_usd=12, avg_price_try=450,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Japon kırtasiye kültürü TikTok'ta patlama yapıyor. Türkiye'de satıcı sayısı hâlâ çok az.",
        ),
        ImportOpportunity(
            "Kawaii Sticker Pack Seti", "Sanat & Dekor",
            demand_score=84, local_supply_score=22, import_score=80,
            monthly_searches_tr=38_000,
            foreign_platforms=["AliExpress", "SHEIN", "Etsy"],
            avg_price_usd=8, avg_price_try=320,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Gen Z ve öğrenciler arasında Kore/Japon tarzı sticker set kültürü yaygınlaşıyor.",
        ),
        ImportOpportunity(
            "Discbound Planner Sistemi", "Defterler & Planlayıcı",
            demand_score=75, local_supply_score=18, import_score=74,
            monthly_searches_tr=22_000,
            foreign_platforms=["Amazon US", "Etsy", "Arc by Staples"],
            avg_price_usd=35, avg_price_try=1_350,
            trend_direction="rising", opportunity_label="Yüksek Fırsat",
            insight="Modüler planlayıcı sistemi Türkiye'de neredeyse hiç yok; ciddi talep mevcut.",
        ),
        ImportOpportunity(
            "Kaligrafi & Brush Pen Seti", "Kalemler & Yazı",
            demand_score=70, local_supply_score=35, import_score=62,
            monthly_searches_tr=18_000,
            foreign_platforms=["Amazon JP", "AliExpress", "Jetpens"],
            avg_price_usd=25, avg_price_try=980,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="El yazısı ve kaligrafi hobisi pandemi sonrası yerleşti; kaliteli ürün az.",
        ),
        ImportOpportunity(
            "Epoxy Resin Sanat Kiti", "Sanat & Hobi",
            demand_score=68, local_supply_score=42, import_score=55,
            monthly_searches_tr=16_500,
            foreign_platforms=["AliExpress", "Amazon DE"],
            avg_price_usd=28, avg_price_try=1_100,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="DIY resin sanatı büyüyor ama kaliteli kit Türkiye'de bulmak güç.",
        ),
        ImportOpportunity(
            "Tomoe River Kağıtlı Defter", "Defterler & Planlayıcı",
            demand_score=62, local_supply_score=12, import_score=66,
            monthly_searches_tr=12_000,
            foreign_platforms=["Jetpens", "Amazon JP", "Galen Leather"],
            avg_price_usd=30, avg_price_try=1_180,
            trend_direction="stable", opportunity_label="Orta Fırsat",
            insight="Dolma kalem hobi topluluğu için premium Japon kağıtlı defterler talep görüyor.",
        ),
        ImportOpportunity(
            "Hobonichi Techo Planner", "Defterler & Planlayıcı",
            demand_score=70, local_supply_score=8, import_score=72,
            monthly_searches_tr=22_000,
            foreign_platforms=["Hobonichi Store", "Amazon JP", "Etsy"],
            avg_price_usd=32, avg_price_try=1_250,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Japon tarzı yıllık planlayıcı kültürü Instagram ve TikTok'ta hız kazanıyor; TR'de resmi satıcı yok.",
        ),
        ImportOpportunity(
            "Mildliner Çift Uçlu İşaretleme Seti", "Kalemler & Yazı",
            demand_score=78, local_supply_score=20, import_score=74,
            monthly_searches_tr=38_000,
            foreign_platforms=["Amazon JP", "Jetpens", "AliExpress"],
            avg_price_usd=24, avg_price_try=935,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Zebra Mildliner bullet journal topluluğunda küresel hit; Türkiye'de yetkili dağıtım yok.",
        ),
        ImportOpportunity(
            "Aesthetic Sticker Book Seti", "Sanat & Dekor",
            demand_score=66, local_supply_score=30, import_score=58,
            monthly_searches_tr=32_000,
            foreign_platforms=["Etsy", "AliExpress", "Amazon US"],
            avg_price_usd=14, avg_price_try=545,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Gen Z planlayıcı dekorasyon trendi; estetik sticker book seti Türkiye'de çeşitli değil.",
        ),
    ],

    "elektronik": [
        ImportOpportunity(
            "Mini Drone (250g altı)", "Akıllı Cihazlar",
            demand_score=90, local_supply_score=52, import_score=83,
            monthly_searches_tr=72_000,
            foreign_platforms=["Amazon US", "AliExpress", "DJI Store"],
            avg_price_usd=150, avg_price_try=5_800,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Drone ithalatı zorlaşıyor; yetkili distribütör olmak büyük rekabet avantajı.",
        ),
        ImportOpportunity(
            "Ring Light + Tripod Kit", "İçerik Üretici",
            demand_score=88, local_supply_score=58, import_score=76,
            monthly_searches_tr=65_000,
            foreign_platforms=["Amazon US", "AliExpress"],
            avg_price_usd=45, avg_price_try=1_750,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="İçerik üretici kitleri hem TikTok hem YouTube kitlesinde Türkiye'de çok aranıyor.",
        ),
        ImportOpportunity(
            "GaN Şarj Aleti 140W+", "Şarj & Güç",
            demand_score=85, local_supply_score=46, import_score=79,
            monthly_searches_tr=55_000,
            foreign_platforms=["Amazon US", "Anker Store", "AliExpress"],
            avg_price_usd=55, avg_price_try=2_150,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="USB-C ekosistemi büyüdükçe tek adaptörde çok cihaz şarjına talep artıyor.",
        ),
        ImportOpportunity(
            "Dijital Çizim Tableti (A5+)", "PC & Yaratıcı",
            demand_score=80, local_supply_score=44, import_score=72,
            monthly_searches_tr=42_000,
            foreign_platforms=["Amazon US", "Amazon DE", "AliExpress"],
            avg_price_usd=80, avg_price_try=3_100,
            trend_direction="rising", opportunity_label="Yüksek Fırsat",
            insight="Dijital illüstrasyon ve içerik üretim trendi ile çizim tableti talebi büyüdü.",
        ),
        ImportOpportunity(
            "USB-C 12-in-1 Hub Dock", "PC Aksesuarı",
            demand_score=78, local_supply_score=50, import_score=65,
            monthly_searches_tr=36_000,
            foreign_platforms=["Amazon US", "AliExpress", "Baseus"],
            avg_price_usd=42, avg_price_try=1_640,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Laptop aksesuarı pazarı genişliyor; kaliteli hub yerel stoklarda yok.",
        ),
        ImportOpportunity(
            "Mekanik Klavye Switch Kiti", "PC & Oyun",
            demand_score=72, local_supply_score=38, import_score=63,
            monthly_searches_tr=28_000,
            foreign_platforms=["Amazon US", "KBDfans", "AliExpress"],
            avg_price_usd=35, avg_price_try=1_360,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Mekanik klavye modding topluluğu Türkiye'de hızla büyüyor; aksesuar arzı yok.",
        ),
        ImportOpportunity(
            "4K Webcam Otofokus", "İçerik Üretici",
            demand_score=82, local_supply_score=40, import_score=74,
            monthly_searches_tr=48_000,
            foreign_platforms=["Amazon US", "Logitech Store", "AliExpress"],
            avg_price_usd=90, avg_price_try=3_510,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Uzaktan çalışma ve içerik üretimi patlamasıyla 4K webcam talebi arttı; TR'de stok yetersiz.",
        ),
        ImportOpportunity(
            "Akıllı Ev Sensör Seti (Zigbee)", "Akıllı Cihazlar",
            demand_score=75, local_supply_score=32, import_score=68,
            monthly_searches_tr=34_000,
            foreign_platforms=["AliExpress", "Amazon DE", "Aqara Store"],
            avg_price_usd=60, avg_price_try=2_340,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Akıllı ev ekosistemine ilgi artıyor; protokol uyumlu sensör seti Türkiye'de kısıtlı.",
        ),
        ImportOpportunity(
            "Taşınabilir Projeksiyon (Mini Laser)", "PC & Yaratıcı",
            demand_score=68, local_supply_score=28, import_score=62,
            monthly_searches_tr=28_000,
            foreign_platforms=["Amazon US", "Nebula Store", "AliExpress"],
            avg_price_usd=140, avg_price_try=5_460,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Ev sinema ve outdoor projeksiyon trendi büyüyor; kompakt laser projektör TR'de az.",
        ),
    ],

    "giyim": [
        ImportOpportunity(
            "Vintage Amerikan Band Tişörtleri", "Üst Giyim",
            demand_score=87, local_supply_score=20, import_score=85,
            monthly_searches_tr=58_000,
            foreign_platforms=["SHEIN", "Depop", "Etsy"],
            avg_price_usd=22, avg_price_try=860,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Y2K ve grunge estetiği TikTok'ta viral; özgün baskılı tişört Türkiye'de üretilmiyor.",
        ),
        ImportOpportunity(
            "Korean Wide-Leg Denim", "Alt Giyim",
            demand_score=85, local_supply_score=38, import_score=78,
            monthly_searches_tr=52_000,
            foreign_platforms=["SHEIN", "Musinsa", "AliExpress"],
            avg_price_usd=30, avg_price_try=1_180,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="K-fashion trendi TikTok'ta dominant; Türk markaları kalıp farkını yakalayamıyor.",
        ),
        ImportOpportunity(
            "Y2K Platform Sneaker", "Ayakkabı",
            demand_score=82, local_supply_score=42, import_score=73,
            monthly_searches_tr=48_000,
            foreign_platforms=["SHEIN", "Amazon US", "Yesstyle"],
            avg_price_usd=38, avg_price_try=1_480,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Platform taban trendde; kaliteli beden açığı ve tasarım özgünlüğü fırsatı veriyor.",
        ),
        ImportOpportunity(
            "Cottagecore Midi Elbise", "Üst Giyim",
            demand_score=76, local_supply_score=28, import_score=70,
            monthly_searches_tr=38_000,
            foreign_platforms=["SHEIN", "Etsy", "Amazon UK"],
            avg_price_usd=28, avg_price_try=1_100,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Romantik ve doğal estetik trendi artıyor; Türk markaları bu segmente girmedi.",
        ),
        ImportOpportunity(
            "Harajuku Grafik Ceket", "Dış Giyim",
            demand_score=72, local_supply_score=15, import_score=71,
            monthly_searches_tr=28_000,
            foreign_platforms=["AliExpress", "Yesstyle", "SHEIN"],
            avg_price_usd=45, avg_price_try=1_760,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Alt kültür modası Türkiye'de gelişiyor; özgün Japon tarzı ceket arzı minimal.",
        ),
        ImportOpportunity(
            "Seamless Spor Tayt Set", "Spor Giyim",
            demand_score=80, local_supply_score=55, import_score=62,
            monthly_searches_tr=44_000,
            foreign_platforms=["SHEIN", "Amazon US", "AliExpress"],
            avg_price_usd=24, avg_price_try=940,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Gym influencer kültürü büyüyor; seamless dokuma tekniği yerli üretimlerde sınırlı.",
        ),
        ImportOpportunity(
            "Capsule Wardrobe Temel Set", "Üst Giyim",
            demand_score=74, local_supply_score=40, import_score=64,
            monthly_searches_tr=32_000,
            foreign_platforms=["Everlane", "Amazon US", "UNIQLO Online"],
            avg_price_usd=55, avg_price_try=2_145,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Minimalist ve sürdürülebilir moda akımı büyüyor; kaliteli temel parça seti Türkiye'de az.",
        ),
        ImportOpportunity(
            "Linen Oversize Takım Elbise", "Dış Giyim",
            demand_score=68, local_supply_score=22, import_score=65,
            monthly_searches_tr=26_000,
            foreign_platforms=["SHEIN", "Amazon UK", "Yesstyle"],
            avg_price_usd=48, avg_price_try=1_870,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Doğal kumaş trendi hız kazanıyor; keten karışımlı oversize takım TR'de üretimi az.",
        ),
        ImportOpportunity(
            "Thermal Base Layer Pro Set", "Spor Giyim",
            demand_score=70, local_supply_score=35, import_score=63,
            monthly_searches_tr=24_000,
            foreign_platforms=["Amazon DE", "Decathlon Online", "AliExpress"],
            avg_price_usd=38, avg_price_try=1_480,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Outdoor ve kayak sporları artıyor; teknik termal içlik seti TR'de sınırlı seçenek.",
        ),
    ],

    "ev_yasam": [
        ImportOpportunity(
            "LED Neon Sign (Kişiselleştirilmiş)", "Aydınlatma & Dekor",
            demand_score=91, local_supply_score=34, import_score=86,
            monthly_searches_tr=70_000,
            foreign_platforms=["AliExpress", "Etsy", "Amazon US"],
            avg_price_usd=45, avg_price_try=1_750,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Oda ve ev ofisi dekorasyonu trendi; özelleştirilebilir neon TikTok'ta çok popüler.",
        ),
        ImportOpportunity(
            "Hidroponik İç Mekan Bahçe Kiti", "Bahçe & Bitki",
            demand_score=80, local_supply_score=22, import_score=78,
            monthly_searches_tr=42_000,
            foreign_platforms=["Amazon US", "AliExpress"],
            avg_price_usd=65, avg_price_try=2_530,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Kentsel tarım ve sürdürülebilirlik trendi; Türkiye'de neredeyse hiç satıcı yok.",
        ),
        ImportOpportunity(
            "Japandi Minimalist Dekor Seti", "Dekorasyon",
            demand_score=78, local_supply_score=30, import_score=74,
            monthly_searches_tr=38_000,
            foreign_platforms=["MUJI", "Amazon JP", "AliExpress"],
            avg_price_usd=40, avg_price_try=1_560,
            trend_direction="rising", opportunity_label="Yüksek Fırsat",
            insight="Japon-İskandinav fusion estetik hız kazandı; orijinal MUJI tarzı ürünlere talep var.",
        ),
        ImportOpportunity(
            "Aesthetic Desk Setup Aksesuar Seti", "Ofis & Masa",
            demand_score=84, local_supply_score=44, import_score=72,
            monthly_searches_tr=52_000,
            foreign_platforms=["Amazon US", "AliExpress", "IKEA Global"],
            avg_price_usd=55, avg_price_try=2_145,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Ev ofisi kültürü estetik masaüstüne yatırım yapıyor; tutarlı set satışı fırsatı.",
        ),
        ImportOpportunity(
            "Smart Plant Sensörü", "Bahçe & Bitki",
            demand_score=72, local_supply_score=24, import_score=68,
            monthly_searches_tr=28_000,
            foreign_platforms=["Amazon US", "AliExpress", "Xiaomi Store"],
            avg_price_usd=22, avg_price_try=860,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Ev bitki meraklısı kitlesinde akıllı bakım teknolojisi popülerleşiyor.",
        ),
        ImportOpportunity(
            "Ritual Mum & Aromaterapi Seti", "Aroma & Rahatlama",
            demand_score=74, local_supply_score=48, import_score=60,
            monthly_searches_tr=32_000,
            foreign_platforms=["Etsy", "Amazon US", "AliExpress"],
            avg_price_usd=32, avg_price_try=1_250,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Wellness ve self-care trendi; sertifikalı kristal ve ritüel setlere talep büyüyor.",
        ),
        ImportOpportunity(
            "Japandi Ahşap Raf Sistemi", "Dekorasyon",
            demand_score=76, local_supply_score=34, import_score=67,
            monthly_searches_tr=36_000,
            foreign_platforms=["IKEA Online", "AliExpress", "Amazon DE"],
            avg_price_usd=55, avg_price_try=2_145,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Minimalist Japon estetik iç mekan tasarımı giderek yaygınlaşıyor; ürün çeşidi TR'de sınırlı.",
        ),
        ImportOpportunity(
            "Akustik Panel Seti (Ev Stüdyosu)", "Ofis & Masa",
            demand_score=70, local_supply_score=28, import_score=65,
            monthly_searches_tr=24_000,
            foreign_platforms=["Amazon US", "AliExpress", "Etsy"],
            avg_price_usd=48, avg_price_try=1_870,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Podcast ve home studio talebi artıyor; estetik akustik panel TR'de hem pahalı hem az.",
        ),
        ImportOpportunity(
            "Ergonomik Oturma Yastığı (Silikon Jel)", "Ofis & Masa",
            demand_score=72, local_supply_score=38, import_score=62,
            monthly_searches_tr=30_000,
            foreign_platforms=["Amazon US", "AliExpress", "Xiaomi Store"],
            avg_price_usd=30, avg_price_try=1_170,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Uzaktan çalışma kültürü ile ergonomik aksesuara talep kalıcı; jel yastık TR'de az.",
        ),
    ],

    "kozmetik": [
        ImportOpportunity(
            "Korean Glass Skin Protokol Seti", "Yüz Bakımı",
            demand_score=93, local_supply_score=38, import_score=88,
            monthly_searches_tr=85_000,
            foreign_platforms=["Yesstyle", "Amazon US", "Olive Young"],
            avg_price_usd=65, avg_price_try=2_530,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="K-beauty rutini Türkiye'deki en hızlı büyüyen kozmetik segmenti; tam set büyük avantaj.",
        ),
        ImportOpportunity(
            "Japon Güneş Kremi (SPF 50+ PA++++)", "Güneş Koruma",
            demand_score=88, local_supply_score=28, import_score=84,
            monthly_searches_tr=72_000,
            foreign_platforms=["Yesstyle", "Amazon US", "Anessa Official"],
            avg_price_usd=18, avg_price_try=700,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Anessa, Biore UV — Türkiye'de bulunmuyor. TikTok'ta milyonlarca görüntüleme aldı.",
        ),
        ImportOpportunity(
            "Press-On Nail Set (Salon Kalitesi)", "Makyaj & Tırnak",
            demand_score=86, local_supply_score=32, import_score=81,
            monthly_searches_tr=68_000,
            foreign_platforms=["Amazon US", "SHEIN", "AliExpress"],
            avg_price_usd=14, avg_price_try=545,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="DIY manikür trendi patlama yaptı; kaliteli press-on nail Türkiye'de bulmak zor.",
        ),
        ImportOpportunity(
            "Gua Sha + Buz Rulosu Seti", "Yüz Masaj",
            demand_score=84, local_supply_score=42, import_score=75,
            monthly_searches_tr=58_000,
            foreign_platforms=["Amazon US", "AliExpress", "Etsy"],
            avg_price_usd=20, avg_price_try=780,
            trend_direction="rising", opportunity_label="Yüksek Fırsat",
            insight="Wellness ve doğal cilt bakımı trendi; sertifikalı taş gua sha setlere talep yüksek.",
        ),
        ImportOpportunity(
            "RF/EMS Yüz Germe Cihazı", "Anti-Aging Teknoloji",
            demand_score=80, local_supply_score=30, import_score=76,
            monthly_searches_tr=45_000,
            foreign_platforms=["Amazon US", "AliExpress", "Nuface"],
            avg_price_usd=85, avg_price_try=3_315,
            trend_direction="rising", opportunity_label="Yüksek Fırsat",
            insight="Ev tipi anti-aging cihaz pazarı global olarak patlıyor; Türkiye'deki yetkili kanal minimal.",
        ),
        ImportOpportunity(
            "Skin Flooding Nemlendirici Seti", "Yüz Bakımı",
            demand_score=78, local_supply_score=45, import_score=66,
            monthly_searches_tr=42_000,
            foreign_platforms=["Amazon US", "Yesstyle", "COSRX Official"],
            avg_price_usd=38, avg_price_try=1_480,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="TikTok'tan çıkan skin flooding rutini Türk tüketicisinde hızla benimseniyor.",
        ),
        ImportOpportunity(
            "Slugging Petrolatum Bariyer Krem", "Yüz Bakımı",
            demand_score=72, local_supply_score=20, import_score=68,
            monthly_searches_tr=28_000,
            foreign_platforms=["Amazon US", "Yesstyle", "iHerb"],
            avg_price_usd=16, avg_price_try=625,
            trend_direction="rising_fast", opportunity_label="Orta Fırsat",
            insight="Slugging rutini TikTok'ta viral; petrolatum bariyer krem TR'de bu isimle satılmıyor.",
        ),
        ImportOpportunity(
            "Scalp Care Saç Derisi Seti", "Saç Bakımı",
            demand_score=74, local_supply_score=30, import_score=67,
            monthly_searches_tr=32_000,
            foreign_platforms=["Amazon US", "Yesstyle", "AliExpress"],
            avg_price_usd=42, avg_price_try=1_640,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Saç derisi sağlığı trendi güç kazanıyor; özel scalp scrub ve serum seti TR'de nadir.",
        ),
        ImportOpportunity(
            "Mineral SPF Vücut Losyonu", "Güneş Koruma",
            demand_score=68, local_supply_score=35, import_score=60,
            monthly_searches_tr=22_000,
            foreign_platforms=["Amazon US", "iHerb", "Yesstyle"],
            avg_price_usd=28, avg_price_try=1_090,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Mineral filtreli vücut güneş kremi clean beauty segmentinde yükseliyor; TR'de az çeşit.",
        ),
    ],

    "spor": [
        ImportOpportunity(
            "Foam Roller + Recovery Set", "Fitness & Gym",
            demand_score=88, local_supply_score=32, import_score=83,
            monthly_searches_tr=62_000,
            foreign_platforms=["Amazon US", "TRX Store", "AliExpress"],
            avg_price_usd=45, avg_price_try=1_750,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="CrossFit ve gym kültürü büyüdükçe recovery araçlarına talep artıyor; kaliteli set Türkiye'de az.",
        ),
        ImportOpportunity(
            "Resistance Band Seti Pro", "Fitness & Gym",
            demand_score=84, local_supply_score=45, import_score=74,
            monthly_searches_tr=55_000,
            foreign_platforms=["Amazon US", "Rogue Fitness", "AliExpress"],
            avg_price_usd=28, avg_price_try=1_090,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Ev egzersizi trendi kalıcılaştı; dayanıklı lastik bant setleri TikTok'ta çok aranıyor.",
        ),
        ImportOpportunity(
            "Adjustable Kettlebell (2–32 kg)", "Fitness & Gym",
            demand_score=80, local_supply_score=28, import_score=78,
            monthly_searches_tr=38_000,
            foreign_platforms=["Amazon US", "Kettlebell Kings", "AliExpress"],
            avg_price_usd=120, avg_price_try=4_680,
            trend_direction="rising", opportunity_label="Yüksek Fırsat",
            insight="Ayarlanabilir kettlebell Türkiye'de neredeyse yok; ev gym kurgulayan segment için büyük fırsat.",
        ),
        ImportOpportunity(
            "Kamp Hamağı + Yağmurluğu Set", "Outdoor & Kamp",
            demand_score=75, local_supply_score=30, import_score=70,
            monthly_searches_tr=32_000,
            foreign_platforms=["Amazon US", "ENO", "AliExpress"],
            avg_price_usd=55, avg_price_try=2_145,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Glamping ve kamp turizmi artıyor; kaliteli hammock seti Türkiye'de az.",
        ),
        ImportOpportunity(
            "Grip Strengthener Pro Set", "Fitness & Gym",
            demand_score=68, local_supply_score=35, import_score=60,
            monthly_searches_tr=24_000,
            foreign_platforms=["Amazon US", "AliExpress"],
            avg_price_usd=22, avg_price_try=860,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Calisthenics ve jimnastik kitlesi hız kazanıyor; el kuvveti ekipmanı arzı yetersiz.",
        ),
        ImportOpportunity(
            "Çok Katlı Kamp Tenceresi Seti", "Outdoor & Kamp",
            demand_score=62, local_supply_score=40, import_score=52,
            monthly_searches_tr=18_000,
            foreign_platforms=["Amazon US", "Sea to Summit", "AliExpress"],
            avg_price_usd=38, avg_price_try=1_480,
            trend_direction="stable", opportunity_label="Takipte",
            insight="Hafif ve katlanabilir kamp mutfağı Türk kampçılar arasında yavaş benimseniliyor.",
        ),
        ImportOpportunity(
            "GPS Spor Saati (Multisport)", "Koşu & Kardiyo",
            demand_score=84, local_supply_score=42, import_score=76,
            monthly_searches_tr=55_000,
            foreign_platforms=["Amazon US", "Garmin Store", "Amazon DE"],
            avg_price_usd=180, avg_price_try=7_020,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Triathlon ve multisport segmenti büyüyor; yetkili Garmin/Suunto dağıtımı TR'de yetersiz.",
        ),
        ImportOpportunity(
            "Vibrasyon Masaj Tabancası Pro", "Fitness & Gym",
            demand_score=86, local_supply_score=44, import_score=77,
            monthly_searches_tr=58_000,
            foreign_platforms=["Amazon US", "Theragun", "AliExpress"],
            avg_price_usd=75, avg_price_try=2_925,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Profesyonel recovery cihazı trendi sporculara yayıldı; orijinal marka TR'de az bulunur.",
        ),
        ImportOpportunity(
            "Trailrunning Ayakkabısı (Karbon Tabanlı)", "Koşu & Kardiyo",
            demand_score=72, local_supply_score=28, import_score=68,
            monthly_searches_tr=30_000,
            foreign_platforms=["Amazon DE", "Salomon Store", "AliExpress"],
            avg_price_usd=130, avg_price_try=5_070,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Dağ koşusu sporu büyüyor; karbon tabanlı trail ayakkabı TR distribütörlerinde kısıtlı.",
        ),
    ],

    "gida": [
        ImportOpportunity(
            "Ceremonial Grade Matcha Seti", "Çay & İçecek",
            demand_score=90, local_supply_score=22, import_score=86,
            monthly_searches_tr=75_000,
            foreign_platforms=["Amazon JP", "Ippodo", "Amazon US"],
            avg_price_usd=35, avg_price_try=1_365,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Matcha latte ve koyu yeşil çay trendi TikTok'ta viral; seremoniel kalite Türkiye'de yok denecek kadar az.",
        ),
        ImportOpportunity(
            "Collagen Peptide Tozu (Grass-Fed)", "Sağlıklı Gıda",
            demand_score=86, local_supply_score=30, import_score=81,
            monthly_searches_tr=65_000,
            foreign_platforms=["Amazon US", "Vital Proteins", "iHerb"],
            avg_price_usd=42, avg_price_try=1_640,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Collagen supplement trendi güçleniyor; onaylı grass-fed kollajen Türkiye'de ithalat zorluğuyla kısıtlı.",
        ),
        ImportOpportunity(
            "Adaptogen Mushroom Karışımı", "Sağlıklı Gıda",
            demand_score=82, local_supply_score=15, import_score=84,
            monthly_searches_tr=52_000,
            foreign_platforms=["iHerb", "Amazon US", "Four Sigmatic"],
            avg_price_usd=38, avg_price_try=1_480,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Lion's mane, chaga gibi mantar adaptogenler biohacking topluluğunda patlıyor; TR'de çok az kaynak.",
        ),
        ImportOpportunity(
            "Manuka Honey UMF 10+ (NZ)", "Doğal & Organik",
            demand_score=78, local_supply_score=20, import_score=74,
            monthly_searches_tr=38_000,
            foreign_platforms=["Amazon NZ", "Amazon US", "Comvita"],
            avg_price_usd=55, avg_price_try=2_145,
            trend_direction="rising", opportunity_label="Yüksek Fırsat",
            insight="Orijinal Yeni Zelanda Manuka balı Türkiye'de büyük talep görüyor; sahte ürün kaygısı kaliteli distribütöre pazar açıyor.",
        ),
        ImportOpportunity(
            "MCT Oil Powder (Ketojenik)", "Sağlıklı Gıda",
            demand_score=75, local_supply_score=35, import_score=65,
            monthly_searches_tr=32_000,
            foreign_platforms=["iHerb", "Amazon US", "Perfect Keto"],
            avg_price_usd=30, avg_price_try=1_170,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Keto ve ketojenik diyet Türkiye'de yavaş ama istikrarlı büyüyor; MCT tozu kaliteli kaynaklarda az.",
        ),
        ImportOpportunity(
            "Electrolyte Tablet Paketi", "Spor Beslenmesi",
            demand_score=70, local_supply_score=42, import_score=58,
            monthly_searches_tr=28_000,
            foreign_platforms=["Amazon US", "Nuun", "AliExpress"],
            avg_price_usd=18, avg_price_try=700,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Koşu ve endurance sporu kitlesinde elektrolit takviyesi benimseniyor; tatlandırıcısız formül az.",
        ),
        ImportOpportunity(
            "Freeze-Dried Meyve Atıştırmalık Seti", "Organik & Doğal",
            demand_score=76, local_supply_score=20, import_score=72,
            monthly_searches_tr=35_000,
            foreign_platforms=["Amazon US", "iHerb", "AliExpress"],
            avg_price_usd=28, avg_price_try=1_090,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Sağlıklı atıştırmalık trendi; dondurarak kurutulmuş meyve TR'de çok az üretici ve ithalatçı var.",
        ),
        ImportOpportunity(
            "Mushroom Coffee Karışımı (Lion's Mane)", "Kahve & Çay",
            demand_score=74, local_supply_score=12, import_score=74,
            monthly_searches_tr=28_000,
            foreign_platforms=["Amazon US", "Four Sigmatic", "iHerb"],
            avg_price_usd=32, avg_price_try=1_250,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Biohacking ve nootropics trendi; mantar kahve karışımı TR'de neredeyse hiç distribütör yok.",
        ),
        ImportOpportunity(
            "Kimchi & Fermente Gıda Başlangıç Seti", "Organik & Doğal",
            demand_score=66, local_supply_score=18, import_score=63,
            monthly_searches_tr=22_000,
            foreign_platforms=["Amazon US", "Etsy", "AliExpress"],
            avg_price_usd=35, avg_price_try=1_365,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="K-food ve fermantasyon trendi Türkiye'ye ulaştı; ev yapımı kimchi seti ve malzemeleri az.",
        ),
    ],

    "oyuncak": [
        ImportOpportunity(
            "Magnetic Tiles XL Set (100+ parça)", "Eğitici & STEM",
            demand_score=89, local_supply_score=28, import_score=84,
            monthly_searches_tr=68_000,
            foreign_platforms=["Amazon US", "AliExpress", "Connetix"],
            avg_price_usd=65, avg_price_try=2_535,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="STEM oyuncak trendi ebeveynler arasında güçleniyor; büyük setler Türkiye'de kaliteli marka ile az.",
        ),
        ImportOpportunity(
            "Stop Motion Animasyon Kiti", "Hobi & Yaratıcı",
            demand_score=82, local_supply_score=14, import_score=81,
            monthly_searches_tr=42_000,
            foreign_platforms=["Amazon US", "Etsy", "AliExpress"],
            avg_price_usd=48, avg_price_try=1_870,
            trend_direction="rising_fast", opportunity_label="Yüksek Fırsat",
            insight="Çocuk içerik üreticiliği ve animasyon hobisi TikTok'la büyüdü; ekipman Türkiye'de yok.",
        ),
        ImportOpportunity(
            "LEGO Special Edition Set (Technic/Creator)", "LEGO & Yapboz",
            demand_score=88, local_supply_score=40, import_score=79,
            monthly_searches_tr=82_000,
            foreign_platforms=["Amazon DE", "LEGO Store", "Amazon UK"],
            avg_price_usd=120, avg_price_try=4_680,
            trend_direction="rising", opportunity_label="Yüksek Fırsat",
            insight="Özel ve lüks LEGO setleri Türkiye'de kısa sürede tükeniyor; stok arbitrajı fırsatı büyük.",
        ),
        ImportOpportunity(
            "Sensory Play & Montessori Seti", "Eğitici & Bebek",
            demand_score=80, local_supply_score=32, import_score=72,
            monthly_searches_tr=45_000,
            foreign_platforms=["Amazon US", "Etsy", "AliExpress"],
            avg_price_usd=40, avg_price_try=1_560,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Montessori ve duyusal oyun bilinci artıyor; ahşap ve doğal malzemeli set arzı yetersiz.",
        ),
        ImportOpportunity(
            "RC Drone Starter (Fotoğraf Çekimli)", "RC & Teknoloji",
            demand_score=76, local_supply_score=38, import_score=65,
            monthly_searches_tr=36_000,
            foreign_platforms=["Amazon US", "DJI Mini", "AliExpress"],
            avg_price_usd=95, avg_price_try=3_705,
            trend_direction="rising", opportunity_label="Orta Fırsat",
            insight="Giriş seviyesi fotoğraf dronları Türkiye'de popülerleşiyor; orta segment büyük boşluk.",
        ),
        ImportOpportunity(
            "Professional Slime Kit (Chemistry Set)", "Hobi & Deneyler",
            demand_score=72, local_supply_score=50, import_score=58,
            monthly_searches_tr=28_000,
            foreign_platforms=["Amazon US", "AliExpress", "Etsy"],
            avg_price_usd=22, avg_price_try=860,
            trend_direction="stable", opportunity_label="Takipte",
            insight="Kimya seti ve slime hobisi Türk çocukları arasında popüler; profesyonel set henüz az.",
        ),
    ],
}


def get_import_opportunities(sector: str) -> list:
    return IMPORT_DATA.get(sector, [])


def get_top_opportunities(sector: str, min_score: float = 65.0) -> list:
    return sorted(
        [o for o in get_import_opportunities(sector) if o.import_score >= min_score],
        key=lambda x: x.import_score, reverse=True,
    )
